version: '3.4'

services:
       
  db_oracle:
    image: container-registry.oracle.com/database/enterprise
    container_name: db_oracle
    user: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=ruben
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
    volumes:
      #- ./oradata:/opt/oracle/oradata
      - ./scripts:/opt/oracle/scripts/setup


  
      


    


      