services:
  keycloak:
    container_name: ruben.test
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_URL: https://ruben.test:8443
      KC_HOSTNAME_ADMIN_URL: https://ruben.test:8443
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_IMPORT: /tmp/realm-export.json
    healthcheck:
      test: ["CMD", "curl", "-f", "https://ruben.test:8443/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start","--https-key-store-password=ruben","--import-realm"]
    volumes: # Ignore if you don't have realm-export.json to migrate data
      - ./certs/ruben.test.crt:/etc/x509/https/tls.crt
      - ./certs/ruben.test.key:/etc/x509/https/tls.key
      - ./realms:/opt/keycloak/data/import
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge