version: '3.4'

services:
       
  db_sports2020:
    image: rdroge/oe_db_sports2020_pro2:12.8.8
    user: pscadmin
    container_name: db_sports2020
    environment:
      - DB_BROKER_PORT=37001
      - DB_MINPORT=4000
      - DB_MAXPORT=4200
    ports:
      - "37001:37001"
      - "4000-4200:4000-4200"
    volumes: 
      - ../app/license/12.8/progress.cfg:/psc/dlc/progress.cfg
      
  db_repl:
    image: rdroge/oe_db_repl:12.8.8
    container_name: db_repl
    user: pscadmin
    environment:
      - DB_BROKER_PORT=37002
      - DB_MINPORT=4250
      - DB_MAXPORT=4350
    ports:
      - "37002:37002"
      - "4250-4350:4250-4350"
    volumes: 
      - ../app/license/12.8/progress.cfg:/psc/dlc/progress.cfg
      - ./db_repl/artifacts:/psc/wrk/repl
      
  db_pro2:
    image: rdroge/oe_db_pro2:12.8.8
    container_name: db_pro2
    user: pscadmin
    environment:
      - DB_BROKER_PORT=37003
      - DB_MINPORT=4450
      - DB_MAXPORT=4550
    ports:
      - "37003:37003"
      - "4450-4550:4450-4550"
    volumes: 
      - ../app/license/12.8/progress.cfg:/psc/dlc/progress.cfg
      - ./db_pro2/artifacts:/psc/wrk/pro2
      

  db_oracle:
    image: container-registry.oracle.com/database/enterprise
    container_name: db_oracle
    user: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=ruben
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_EDITION=ee
    volumes:
      - ./db_oracle/oradata:/opt/oracle/oradata
      - ./db_oracle/scripts:/opt/oracle/scripts/setup



  pas_pro2:
    image: rdroge/openedge_pas_pro2:6.5.2
    container_name: pas_pro2
    ports:
      - "9991-9993:9991-9993"
    volumes: 
      - ../app/license/12.8/progress.cfg:/usr/dlc/progress.cfg
      - ./logs/:/install/pro2/Pro2Web/logs
    
    depends_on:
      - db_sports2020
      - db_repl
      - db_pro2
      - db_oracle

  
      


    


      