name: Run Gradle on PRs
on:
  push:
    branches: [ main ]
    paths: 
      - mttenant/**
      - .github/workflows/main.yml

jobs:
  sports2020db:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/rdroge/oe_db_sports2020:12.8.6
      options: --user pscadmin --hostname sports2020db
      env:
        DB_BROKER_PORT: 15010
        DB_MINPORT: 3000 
        DB_MAXPORT: 5000
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      ports:
        - 15010:15010
        - 3000-5000:3000-5000
    steps:
      - name: Echo
        run: echo 'database is being started'
  gradle:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/progressofficial/oe_compiler:12.8.6
      options: --user root
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4.2.2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.12.0
    - name: Execute Gradle build
      run: ./gradlew build compileCode
    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path:
          /tmp/dist
  docker:
    needs: gradle
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout Everything again
        uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/mttenant/pas_mttenant
      - run: 
          ls ${{ github.workspace }}/mttenant/pas_mttenant/dist
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}/mttenant/pas_mttenant"
          push: true
          tags: rdroge/openedge_pas_mttenant:${{ vars.OE_VERSION }}

