name: Run Gradle on PRs
on:
  push:
    branches: [ main ]
    paths: 
      - mttenant/**
      - .github/workflows/*.yml

jobs:
  gradle:
    runs-on: ubuntu-latest
    container: progressofficial/oe_compiler:12.8.4
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build compileCode
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path:
          /tmp/dist
  docker:
    needs: gradle
    runs-on: ubuntu-latest
    steps:
      - 
        name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout Everything again
        uses: actions/checkout@v4
      -
        name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/mttenant/pas_mttenant
      - run: 
          ls ${{ github.workspace }}/mttenant/pas_mttenant/dist
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}/mttenant/pas_mttenant"
          push: true
          tags: rdroge/openedge_pas_mttenant:${{ vars.OE_VERSION }}

