name: Run Gradle on PRs
on:
  push:
    branches: [ main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    container: rdroge/jenkins-agent:jdk17oe127
    steps:
    - uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build compileCode
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path:
          /tmp/dist  
